###############################################
# Documentation Makefile
###############################################

DOCUMENT_FILE=design_document

all:
	pdflatex $(DOCUMENT_FILE).tex
clean:
	rm -f *.out *.aux *.toc *.pdf *.log *~ \#*