###############################################
# Documentation Makefile
###############################################

DOCUMENT_FILE=write_up

all:
	pdflatex $(DOCUMENT_FILE).tex
	pdflatex $(DOCUMENT_FILE).tex

clean:
	rm -f *.out *.aux *.toc *.pdf *.log *~ \#*