######################################################
# Makefile for project
######################################################

all: events usage

events:
	./events.py

usage:
	./usage.py

forensics:
	./attribute_forensics.py

clean:
	rm -f *~ \#* *.txt *.csv