######################################################
# Makefile for project
######################################################

all:

machine_events:
	./machine_events.py

clean:
	rm -f *~ \#* *.txt *.csv