#############################################
# Problem Set 2
#############################################

DOC_DIR=doc
SRC_DIR=src

all: doc

doc:
	cd $(DOC_DIR) && $(MAKE)

run:

test:

clean:
	cd $(DOC_DIR) && $(MAKE) clean
	rm -f *~ \#*