####################################################
# Makefile for src director
####################################################

all: test

test:
	python lock_client_test.py

clean:
	rm -f *~ \#*