#####################################################################3
# CSE 550 Autumn 2014
#
# Problem Set 2
# Author: Vincent Lee
#####################################################################3


all:
	run
test:
	python client_test.py
	python acceptor_test.py
	python proposer_test.py
run: 
	echo "TODO"
clean:
	rm -f *~ \#* *.o *.txt